-- Enable Row-Level Security on all tables.
-- This app uses Prisma (direct PostgreSQL connection as DB owner), so RLS
-- is bypassed for normal app queries. Enabling RLS blocks unauthenticated
-- access through the Supabase REST API (PostgREST).

ALTER TABLE "Account" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "VerificationToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Post" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Media" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AudioTrack" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlatformToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PublishRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PublishAnalytics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImportJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BulkAnalyzeJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BulkCaptionAnalyzeJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DriveSync" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PostAnalytics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FacebookComment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WeeklyPlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WeeklyPlanSlot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PostRating" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyBrief" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Conversation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Message" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Todo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserMemory" ENABLE ROW LEVEL SECURITY;

-- Also revoke direct access from the anon and authenticated roles
-- to ensure no data leaks through the Supabase Data API.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
